const TherapistList =
[
  {
    "id": "1",
    "name": "Paige Williams",
    "title": "Financial Coach ",
    "bookingURL": "https://millenniummoney.myclickfunnels.com/bookacall1",
    "expertise": "Debt Management, Saving, Investing",
    "certifications": "Bachelor’s Degree in Biopsychology, Master’s Degree in Medical Sciences – Liberty University (2022), Founder of the Millennium Money Master Program, Helped over 100 clients",
    "song": "\"Upgrade U\" by Beyonce",
    "yoe": "8",
    "clientele": "Early to mid-career professional women in their mid-20s and 30s who are looking to build long-term wealth. Income Level: Annual incomes ranging from $40,000 to $100,000. Occupation: A mix of salaried professionals, entrepreneurs, and freelancers. Challenges: Struggle with balancing short-term wants and long-term goals, navigating credit, and establishing clear financial systems.",
    "longBio": "I'm a passionate Money Coach and Online Content Creator dedicated to empowering women to take full control of their finances and build long-term wealth. In just 5 months, I paid off $3,000 in credit card debt, saved $5,000 in an emergency fund, and invested $10,000—all while juggling grad school and part-time jobs. This transformation inspired me to create the Millennium Money Master Program, a high-impact coaching program that has helped over 100 clients achieve financial confidence through crushing debt, investing, and strategic money management. My mission is to make personal finance fun, attainable, and attractive while inspiring others to take action, no matter where they’re starting",
    "previewBlurb": "Empowering women to crush debt, invest smartly, and build lasting financial confidence!",
    "profileUrl": "/experts/PaigeW.jpg"
  },
  {
    "id": "2",
    "name": "Constance McConnell",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/constance-courage2heal/30min",
    "expertise": "Major life and financial changes, Budgeting ",
    "certifications": "Licensed Clinical Social Worker, Certified Financial Social Worker, Therapist",
    "song": "\"Golden\" by Jill Scott",
    "yoe": "10",
    "clientele": "20-65 years old. Historically marginalized populations (Black, Latinx, Native American, Women, LGBTQ+ communities). Identify with the upper-middle socioeconomic class. Doesn't mind telling their story via mindful journaling.",
    "longBio": "Constance is a LCSW, author, business owner, financial therapist and creative who specializes in working with individuals who are experiencing major life and financial changes. She is also a certified financial social worker and helps clients who want to improve their relationship with money. Constance is the author of a guided journal called, \"My Very Own Affirming Guided Journal A-Z” and launched a t-shirt line with designs that feature positive affirmations. She has practiced for 12 years and most of her clients are a part of the BIPOC and LGBTQ+ communities. Constance has been a featured professional guest on the following podcasts and media platforms: “Personal Finance with Leila”, “Budget Simple” “SocialWorkerRants” “AboutthatWallet”and “FIRE Social Worker.”",
    "previewBlurb": "A financial therapist and author, enhancing relationships with money through empowerment! ",
    "profileUrl": "/experts/Constance.jpg"
  },
  {
    "id": "3",
    "name": "Michele Paiva",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/paiva/corporate-client",
    "expertise": "Business Management, Family Planning, Couples, Clinical Autism Specialist",
    "certifications": "Licensed Psychotherapist specializing in Trauma and Financial Therapy, Certified Clinical Autism Specialist, Certified Financial Educator, Certified Financial Social Worker, Lifestyle Science Certified, Certified Clinical Meditation (Through University of Mass)",
    "song": "\"Ain't Misbehavin\" by Fats Waller",
    "yoe": "10",
    "clientele": "21 - 55. Mid Income. Millennials enjoy that I've been there, done that, and lived to tell; older clients appreciate that I've already put children through college, invested in property, etc., beyond \"just getting out of debt\" etc.",
    "longBio": "Michele Paiva is a financial therapist, trauma therapist, fractional CMO, and publicist with over 30 years of experience helping individuals and businesses thrive. Millennials value her relatable, \"I’ve been there\" approach, while Boomers appreciate her wisdom from successfully living through life’s financial challenges. Michele’s work focuses on uncovering the emotions beneath financial struggles, resolving couples' money conflicts, and empowering clients to showcase their value, build abundance, and create lasting change. Michele has autism and is also a certified clinical autism specialist who enjoys helping neurodivergent employees regain their feelings and finances. In 2023, she was voted top 100 publicists out of 14,000. She likes Tofu.",
    "previewBlurb": "A casual approach to emotional depth and elegant living!",
    "profileUrl": "/experts/Michele.jpeg"
  },
  {
    "id": "4",
    "name": "Justin DeFoor",
    "title": "Financial Coach ",
    "bookingURL": "https://calendly.com/tgcfinancialgroup ",
    "expertise": "Budgeting, Savings, Growth, Credit, Tax Planning",
    "certifications": "MBA, Certificate in Life Coaching, Life Insurance License",
    "song": "\"You Will Win\" by Jekalyn Carr",
    "yoe": "5",
    "clientele": "18-50. Income from $18,000 to $100,000. Any ethnicity and background.",
    "longBio": "I started my entrepreneur lifestyle as a business consultant. After about a year I entered into the financial services industry to help more people. I believe my purpose is to help people become financially free and create generational wealth. Through this I have helped a lot of individuals and families build the lifestyle that they want by understanding the fundamentals of finance and creating good financial habits that will benefit them and their children. I've been in this industry for 5 years and now look to build people mentally, emotionally, physically, spiritually, and financially to walk in balance while living in purpose in every area of their lives.",
    "previewBlurb": "Empowering financial freedom and generational wealth for all!",
    "profileUrl": "/experts/JustinD.jpeg"
  },
  {
    "id": "5",
    "name": "Aitzarelys Negrón",
    "title": "Financial Coach ",
    "bookingURL": "https://StrategiesandTEA.as.me/?appointmentType=72189521",
    "expertise": "Entrepreneurship, Paycheck to purpose, Mindset shifts, Money audits, Bugeting, Business Bookkeeping, Business essentials, Profit Management, Debt Management, Burnout, Cash Flow",
    "certifications": "Certified Public Accountant (CPA), QuickBooks Online Certified, ProAdvisor, Accredited Financial Counselor (Studying/In Process)",
    "song": "\"Level Up\" by Ciara",
    "yoe": "10",
    "clientele": "25–45 years old. Professionals, Aspiring entrepreneurs. Income: $70,000–$150,000+.",
    "longBio": "Aitza is a passionate financial coach, accountant, and entrepreneur dedicated to helping professionals and aspiring business owners achieve financial clarity and time freedom. With a background as a CPA and years of experience in personal finance and business management, she empowers her clients to bridge the gap between their current reality and their ideal lifestyle. Aitza’s journey into financial coaching was inspired by her own transformational story—turning her life around in high school with the support of a mentor, she now dedicates her career to helping others see possibilities and take control of their futures. Her coaching program, moneyFLOW$™ Academy, guides high-earning professionals through mastering personal finances, reducing debt, and building sustainable businesses. In addition to coaching, Aitza specializes in bookkeeping, bookkeeping diagnostics, Profit First implementation, and financial clean-ups, ensuring business owners have the tools they need for long-term profitability. Her clients have achieved remarkable results, from saving thousands of dollars to confidently launching businesses that align with their goals and values. Aitza’s mission is to create financial confidence and economic resilience for her clients, equipping them to build wealth and lead change for themselves, their families, and their communities.",
    "previewBlurb": "Transforming finances, empowering dreams, and creating lasting wealth!",
    "profileUrl": "/experts/Aitzarelys.jpeg"
  },
  {
    "id": "6",
    "name": "Maureen Kelley",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/mk-maureenkelley ",
    "expertise": "Family, Wealth Management, Positive Psychology",
    "certifications": "BS, University of Rhode Island Graduate Cert Financial Therapy, Kansas State Univ Executive Women's Leadership, The Wharton School - Certification Applied Positive Psychology, Univ of Penn Certified Financial Therapist (CFT), Certified Financial Behavior Specialist (FBS), Accredited Wealth Management Advisor (AWMA), Certified Family Wealth Advisor (CFWA), Certified Family Coach(CFC), Certified Co-Parenting Specialist",
    "song": "\"You've Got a Friend In Me\" by Randy Newman",
    "yoe": "10",
    "clientele": "People from all walks of life. Young adults, individuals, co-parents, couples and families. She has helped those who struggle with making ends meet, people navigating divorce issues, to multi-generational complex families of wealth.",
    "longBio": "Maureen Kelley has more than 30 years’ experience helping families navigate the complex intersection of economics and emotions. As a seasoned family dynamics coach and family wealth consultant, she’s dedicated to creating a safe space for you to share the ups and downs of your financial journey. Maureen works to dismantle the stigma surrounding these conversations, making hard-to-talk-about topics a lot easier. Having held senior positions at financial institutions like BOK Financial Private Wealth and Wells Fargo Private Bank, Maureen offers years of expertise in wealth management and positive psychology, helping you improve your financial life by improving your relationship with yourself and your loved ones. Working with Maureen, you’ll rewrite your “money scripts”—the narratives we develop around wealth in childhood—and better understand how your past shapes your present views on money. As the founder of a family dynamics and financial coaching practice, Maureen’s dedication to family is evident. Her services have been utilized by people of all walks of life, including young adults, co-parents, couples, and multi-generational families. Through financial therapy and coaching, you can overcome anxiety, guilt or shame surrounding money, and develop financial literacy to achieve holistic success. With less stress around money management, you can spend more time focusing on the things that really matter, like spending time with the ones you love.",
    "previewBlurb": "Transform your relationship with money to enhance life and strengthen family connections!",
    "profileUrl": "/experts/Maureen.jpeg"
  },
  {
    "id": "7",
    "name": "Tiffany Grant",
    "title": "Financial Coach ",
    "bookingURL": "https://calendly.com/moneytalkwitht/coaching",
    "expertise": "Personal Finance, Side hustles, Business growth, Money Management",
    "certifications": "MBA, AFC, SHRM-CP",
    "song": "\"Lean on Me\" by Bill Withers",
    "yoe": "8",
    "clientele": "25-45, any gender. Income up to $150,000. Looking for help with budgeting and goal setting.",
    "longBio": "Tiffany Grant, AFC®, is a dedicated Accredited Financial Counselor, sought-after speaker, and founder of Money Talk With Tiff. Renowned for her ability to make personal finance approachable and relatable, Tiffany has made significant contributions as a financial educator, coach, blogger, and podcaster. Her expert advice on side hustles, business growth, and money management has been featured on platforms like Forbes, CNBC, Yahoo Finance, Business Insider, MSN, and ESSENCE. Tiffany's passion lies in empowering others to gain control over their finances through practical education and down-to-earth insights. Her engaging style and actionable guidance have helped countless individuals build financial confidence and clarity. Beyond her professional accolades, Tiffany’s academic background includes a Bachelor of Business Administration and Management from the University of North Carolina at Pembroke and a Master of Business Administration (MBA) from the University of North Carolina at Greensboro. She also holds the SHRM-CP credential and is a certified Lean Six Sigma Yellow Belt, reflecting her diverse expertise and dedication to continuous learning.",
    "previewBlurb": "Empowering financial freedom through practical education and relatable money management insights!",
    "profileUrl": "/experts/TiffanyGrant.jpeg"
  },
  {
    "id": "8",
    "name": "Tyana Ingram",
    "title": "Financial Social Worker",
    "bookingURL": "https://calendly.com/tingram-xdc/financial-wellness-counsulting",
    "expertise": "Financial Healing, Mindset, Financial Wellness",
    "certifications": "ASW (Associate Clinical Social Worker), CFSW (Certified Financial Social Worker), CFEI (Certified Financial Educational Instructor)",
    "song": "\"Optimistic\" by Sounds of Blackness",
    "yoe": "10",
    "clientele": "Underserved communities. Professionals. Low-middle income. Women entrepreneurs. Domestic violence survivors. Christian.",
    "longBio": "Tyana Ingram is the CPO and Co-Founder of the Financial Social Work Collaborative™ and is the Founder of Financial Healing Circles™, a financial wellness business that empowers underserved communities to heal their money wounds and achieve financial peace of mind. Her mission is to disrupt the cycle of money trauma utilizing the Financial Social Work framework combined with a mind-body-soul approach to deliver financial wellness services. She is an Associate Clinical Social Worker, Certified Financial Social Worker, and Financial Education Instructor based out of California and has dedicated her career to equipping people with the tools they need to live their best lives.",
    "previewBlurb": "Empowering communities to heal money wounds and achieve financial peace through holistic wellness!",
    "profileUrl": "/experts/TyanaIngram.jpeg"
  },
  {
    "id": "9",
    "name": "Vince Hollerman",
    "title": "Financial Coach ",
    "bookingURL": "https://app.acuityscheduling.com/schedule/8d3ad975",
    "expertise": "Previously investment and life insurance licensed. (No longer holds licenses)",
    "certifications": "Previously investment and life insurance licensed. (No longer holds licenses)",
    "song": "N/A",
    "yoe": "8",
    "clientele": "25-45 year olds. 50/50 Male to Female. Income level: $50,000+. 9-5 Professionals, Small Business Owners.",
    "longBio": "Vince Hollerman, Coach Vince, is a Money Coach & Digital Creator specializing in helping millennials sort or their finances and stream line their path to financial freedom. He focuses on instilling great money habits for saving, budgeting & investing by developing your money mindset and putting money systems into place to help you reach your financial goals. With over 600,000 followers and supporters across social media, Vince has built a successful online Financial Education & Coaching Platform called IAmYourMoneyCoach.com that impacts and transforms the finances of those looking to take back control of their money.",
    "previewBlurb": "Empowering millennials to achieve financial freedom through mindset shifts and effective money systems!",
    "profileUrl": "/experts/vince.jpg"
  },
  {
    "id": "10",
    "name": "Jaelyn Vickery",
    "title": "Financial Therapist",
    "bookingURL": "https://outlook.office.com/bookwithme/user/dbdc3761a936461793e506df25358b91@illinois.edu/meetingtype/_T3Sy3d-XkuptOwOzGAk-A2?bookingcode=3c26242c-7647-4395-9aea-135ffebbf651&anonymous&ep=mLinkFromTile ",
    "expertise": "Dimensional Wealth, Holistic abundance, Financial empowerment, Financial Therapy, Mindset",
    "certifications": "B.A. Liberal Arts & Sciences, Psychology M.S. Social Work, Healthcare/Mental Health LSW, Licensed Social Worker, Certified Integrated Behavioral Health Technician, 8 Dimensions of Wellness Guidebook Author (UIUC), CFT-I - Certified Financial Therapist *In Process, AFC - Accredited Financial Counselor *In Process",
    "song": "\"You Make My Dreams\" by Hall & Oates",
    "yoe": "1",
    "clientele": "Aged 18-45 who are navigating life transitions. Diverse genders. Diverse income levels and backgrounds.",
    "longBio": "Jaelyn (Jae) Vickery is a dynamic force in the world of holistic wellness and financial empowerment. As a financial therapist, entrepreneur, and creator of the acclaimed podcast Finance Fitness Finesse, Jae is dedicated to helping individuals build their wealth with wellness. Through her business, Dimensional Wealth LLC, she champions a momentum mindset—encouraging actionable steps toward abundance and longevity rather than waiting on fleeting motivation. With extensive experience researching and working in eating disorder therapy, Jae has explored the complex relationship between eating disorders and financial strain. She particularly enjoys working with individuals who seek a higher understanding of themselves and value the accountability to embrace the challenge of building and sustaining new habits. Jae is dedicated to helping individuals break free from the cycle of compulsion, consumption, and control. Jae’s straightforward compassionate accountability approach brings purpose to every conversation to help her network diversify their knowledge portfolios. She’s here to help you connect the dots between wealth and wellness and isn’t afraid to tell you why “you’re not woke, you’re broke.” In her free time, Jae embraces free movement through exercise, explores nature with her dog Bibble, and indulges her love for art. A devoted plant mom and chess enthusiast, she brings creativity and strategy to everything she does.",
    "previewBlurb": "Empowering holistic wealth and wellness through financial therapy and mindset transformation!",
    "profileUrl": "/experts/jaelyn.jpg"
  },
  {
    "id": "11",
    "name": "Shani Tené ",
    "title": "Financial Coach ",
    "bookingURL": "https://shanitene.com/levelup",
    "expertise": "Budgeting, Saving, Investing, Debt reduction",
    "certifications": "N/A",
    "song": "Stronger Together",
    "yoe": "10",
    "clientele": "Millennials & Gen X, Middle Class Females",
    "longBio": "Shani Tené is a passionate Money Coach, financial educator and speaker, dedicated to helping individuals achieve financial freedom through a faith-inspired approach. Merging extensive financial knowledge with spiritual principles, Shani empowers clients to enhance their income, manage debt, and invest wisely, ensuring their financial goals reflect their personal values. Her holistic strategy not only boosts financial health but also fosters spiritual richness, guiding clients towards sustainable wealth and true independence.",
    "previewBlurb": "Empowering financial freedom through faith-based coaching and holistic money management!",
    "profileUrl": "/experts/ShaniT.jpg"
  },
  {
    "id": "12",
    "name": "BreAnna Plummer",
    "title": "Financial Social Worker",
    "bookingURL": "https://calendly.com/bplummerconsciouschoicestherapy/financialwellness",
    "expertise": "Money Mindset, Budgeting, Saving, Debt ",
    "certifications": "Licensed Master Social Worker (LMSW), Certified Financial Social Worker (CFSW), Certified Domestic Violence Specialist Level 1 (CDVSI)",
    "song": "\"One Step At A Time\" by Jordan Sparks",
    "yoe": "9",
    "clientele": "Age 30-45 who identify as BIPOC. Income levels range from $100,000-$300,000 annually. No guidance or support in improving financial stability and saving habits. Symptoms such as stress, depression, PTSD and anxiety = main money concern.",
    "longBio": "I have been a clinical social worker and advocate for wellness for 9 years. I earned my BSW (2015) and MSW (2017) from Wayne State University. Over my career I have worked with families of Head Start, survivors of crime, survivors of homelessness and financial trauma, planned community events for survivors and managed programs for suicide prevention. I became a certified financial social worker in August 2024. The highs and lows of my own financial journey led me to practice financial social work. I utilize my skills and professional expertise to help clients gain mental and financial stability through one-on-one support. Working to help individuals have less stress and anxiety about money while decreasing their debt and increasing their savings is my passion. In our 45-60 minute one on one sessions, clients will gain holistic and practical tools to transform into a mindful money manager!",
    "previewBlurb": "Empowering mental and financial stability through holistic 1on1 support and practical tools!",
    "profileUrl": ""
  },
  {
    "id": "13",
    "name": "Monica Bradshaw ",
    "title": "Financial Coach ",
    "bookingURL": "https://calendly.com/mbradshaw-2/rpcoaching",
    "expertise": "Wealth building, Retirement",
    "certifications": "Certified Financial Coach, Certified Trauma Coach",
    "song": "\"Titanium\" by David Guetta",
    "yoe": "3",
    "clientele": "45 - 60 years old. Sandwich generation. Household income $120k.",
    "longBio": "I began my career in 1994 at Paulson Investments and have since built a diverse background, including roles as a licensed stockbroker, real estate agent, trauma counselor, IT manager, certified Scrum Master, and bookkeeper. Despite high income and prestigious credentials, I found myself struggling financially, with no progress toward generational wealth and living paycheck to paycheck. After confronting my money trauma and mindset, I developed a transformational approach combining financial strategies with personal growth techniques. This led me to coach others, incorporating neuropsychology, manifestation, and assessments. I help people go beyond financial knowledge to achieve true transformation, enabling lasting success. My journey has been shaped by extensive study in areas like NLP, neuroscience, and wealth-building, and I now share my step-by-step method to help others achieve financial and personal bliss. ",
    "previewBlurb": "Transforming financial struggles into lasting success through holistic coaching and personal growth!",
    "profileUrl": "/experts/MonicaB.jpeg"
  },
  {
    "id": "14",
    "name": "Haylie Castillo",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/hayliecastillo/20-minute-intital-consultation",
    "expertise": "Financial Trauma, Psychotherapy, Financial education, Coaching ",
    "certifications": "Certified Financial Therapist™ Professional, LSWAIC; MSW; Currently pursuing the Trauma of Money™ Professional Certification",
    "song": "\"All I Know So Far\" by Pink",
    "yoe": "2",
    "clientele": "Women. Gender expansive individuals. Clients who feel they make \"enough\" money. Those who still struggle with complicated feelings about money and success.",
    "longBio": "Hi! I’m Haylie (she/her). My mission is to help people heal their relationship with money so that they can create the life they truly want to live. I am passionate about helping people reclaim freedom and agency over their lives, and I believe a crucial part of that is having a healthy relationship with money. As a financial therapist, I help people work through their financial trauma and shift their negative emotions around money. I support them in building a healthy relationship with money by relearning how to have a healthy relationship with themselves. We work together to redefine their concept of success, and identify financial goals that align with their values. My clients long to experience freedom and agency in their lives, and their relationship with money is the one area that they haven’t been able to figure out. Many of them have financial trauma holding them back from chasing their dreams. Our families, communities, and society at large hand us a lot of default beliefs about money and success, but these default beliefs no longer work for my clients. You may have looked into personal finance, but whether it’s impulsive spending, avoiding your bank statements, or grappling with indecisiveness, you still find yourself struggling and secretly wonder if you’ll ever feel good about money. Trying to navigate the complicated, overwhelming feelings of depression, shame, anger, or anxiety around money is exhausting. As both a financial coach and trained psychotherapist, I offer a unique experience to those who work with me. First, we will work together to define your beliefs about money and develop a healthy relationship with money. I provide a shame-free space to work through your emotions and psychology around money, and I will help you cultivate a healthy, positive money mindset. Then, through personalized financial education and coaching, I will help you create a money practice that is realistic and aligned with your values and goals. My clients end their work with me feeling at ease with their finances and with the confidence and clarity to use money as a resource to nourish the life they want to live. You deserve to have a relationship with money that gives you confidence and joy. You can have a relationship with money that is peaceful, empowering, and allows you to chase your dreams. If this is you, schedule your free consultation and let’s chat!",
    "previewBlurb": "Heal your money mindset, reclaim your freedom, and live your dreams!",
    "profileUrl": ""
  },
  {
    "id": "15",
    "name": "Sarah Carr",
    "title": "Financial Therapist",
    "bookingURL": "https://sarahcarr.as.me/schedule.php",
    "expertise": "Investment education, Debt, Bubgeting, Saving ",
    "certifications": "Certified Financial Planner (TM), Certified Financial Therapist (TM)",
    "song": "\"Got It In You\" by Banners",
    "yoe": "10",
    "clientele": "Mid 20s, 30s, 40s, and 60-70s. Income level varies.",
    "longBio": "Using financial therapy tools we explore how and why one relates to money the way they do. We look at how beliefs, values, and money histories shape financial decisions and work toward aligning one's resources with the life they are creating. We also work on communication skills when it comes to expressing financial concerns and needs. The work often includes creating a financial snapshot, establishing new spending patterns, and learning techniques to improve goal setting and achievement. I can provide investment education and advice as well. My base session rate is $120 an hour. I also provide packages of services. My most common package includes three personalized one-on-one sessions with financial planning/analysis (financial snapshot, cash flow review, debt analysis, goal setting, etc), and that is typically $540. I can create custom packages and can offer a sliding scale when necessary. I also offer payment plans, typically dividing the cost over the number of sessions. I can offer investment management (though I only do that in select cases where it makes sense for the client), that fee is an asset under management fee typically of 1.5%",
    "previewBlurb": "Transforming financial wellness through compassionate guidance and personalized money healing!",
    "profileUrl": "/experts/Sarah_Carr_Headshot.jpeg"
  },
  {
    "id": "16",
    "name": "LaQueshia Clemons",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/lclemonslcsw/meeting",
    "expertise": "Financial Therapy, Social Work",
    "certifications": "LCSW, AFC",
    "song": "\"Unbreakable\" by Alicia keys",
    "yoe": "8",
    "clientele": "Female, 35, African American. Might be married with children. Has a degree. Makes good money but not sure where it goes.",
    "longBio": "LaQueshia Clemons is a LCSW, Trauma of Money Certified, and Financial Counselor, who guides individuals and couples towards financial well-being and emotional resilience. As the founder of Freedom Life Therapy and Wellness, she helps clients explore money-related emotional and behavioral patterns. Through engaging workshops and speeches, LaQueshia empowers others to understand their unique money stories, emphasizing the profound influences shaping financial decisions. Featured in media outlets like Word in Black, Nerd Wallet, and Yahoo Finance, her dynamic and warm approach transforms lives and fosters healthy money relationships. Outside work, LaQueshia enjoys cooking, adding zest to life through culinary adventures.",
    "previewBlurb": "Heal your money mindset, empower your future, and savor life's journey!",
    "profileUrl": "/experts/LaQueshiaClemons.jpeg"
  },
  {
    "id": "17",
    "name": "Kelly Reddy-Heffner",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/kelly-steelcitywc/hello",
    "expertise": "Life transition guidance, Combining finances with a Partner, Student loan strategies, Divorce planning, Loss of a loved one planning, Accountability Coaching, Budgeting, Money and behavior, Goal setting and measuring, Building good money habits, Negotiation strategies",
    "certifications": "CFP, CDFA, CSLP, CFT, additional certificate in Strategic Negotiation",
    "song": "\"Lean on Me\" by Bill Withers",
    "yoe": "8",
    "clientele": "Trend toward early career to pre-retirement and encountering some type of life transition. There is an appreciation for an empathetic and energetic professional to provide financial guidance during a time of increased stress.",
    "longBio": "Kelly is a CERTIFIED FINANCIAL PLANNER(TM) professional, Certified Student Loan professional (R), a Certified Divorce Financial Analyst (R) practitioner, and Certified Financial Therapist-1(TM). She maintains those credentials with annual continuing education programs to stay up to date and would consider herself a lifelong learner. Life credentials include growing up in a home with a single mom who worked miracles with financial resources available, business ownership, college funding and student loan survival, buying and selling property and cars, military service member household with multiple PCS moves, divorced family members and friends, life’s twists and turns.",
    "previewBlurb": "Empowering financial journeys through expertise, empathy, and life experience!",
    "profileUrl": "/experts/Kelly_Reddy_Heffner.jpeg"
  },
  {
    "id": "18",
    "name": "George Blount",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/georgeblount",
    "expertise": "Financial Therapy (with or without financial trauma) Financial Education, Coaching",
    "certifications": "Doctorate",
    "song": "\"Scenario\" by Tribe Called Quest",
    "yoe": "10",
    "clientele": "Generation X, male or female. Earning between $75,000 and $150,000. ",
    "longBio": "Dr. George M. Blount is a financial therapist, the Founder of nBalance Financial, and a researcher of finance's emotional, psychological, behavioral, and relational elements. Dr. Blount is also an accomplished educator, serving as an Adjunct Professor and Lecturer in Personal Finance, Finance, Managerial Accounting, and Behavioral Finance at several universities. He holds a Doctor of Business Administration (DBA) and an MBA from Walden University, as well as a Bachelor of Science (BS) and an Associate of Science (AS) from Johnson and Wales University. Dr. George Blount has spent over 20 years in the financial services industry, obtaining a wealth of knowledge in retirement planning, business development, and strategy. He served on the MA Financial Literacy Task Force in 2015, appointed by MA Treasurer Deb Goldberg, and was named one of the top 100 people of Finance 2020, an award by Top 100 magazine. TEDx Talk: https://youtu.be/KSCAuHC1-P4",
    "previewBlurb": "Transforming financial wellness through emotional intelligence and strategic money mindset!",
    "profileUrl": "/experts/GeorgeBlount.jpg"
  },
  {
    "id": "19",
    "name": "Tamoa Danielle Smith",
    "title": "Financial Therapist",
    "bookingURL": "https://api.leadconnectorhq.com/widget/booking/fQXXP7vrPawH8NQguqXR",
    "expertise": "Financial Therapy, Couples Financial Therapy, Corporate Financial Wellness Program, Emotional and practical financial support, Confidence building, Stress management",
    "certifications": "Licensed Clinical Mental Health Therapist",
    "song": "\"Unstoppable\"",
    "yoe": "10",
    "clientele": "Typically between 30 to 55 years old, focused on individuals navigating significant life transitions such as marriage, divorce, or career changes, which impact their financial stability. I predominantly serve female clients, although my services are inclusive and beneficial to all genders, with a focus on empowering women to take charge of their financial health, especially post-divorce or during major life adjustments. The clients I work with range from middle to upper-middle class, with annual incomes between $40,000 to $120,000, often in stages of rebuilding or enhancing their financial independence and security. Primarily based in suburban areas across the United States, with a significant number located in the Southeast, my clients are diverse in their careers, including sectors like healthcare, education, and small business ownership. They seek to balance professional growth with financial stability and are particularly interested in financial therapy to address and heal from financial trauma, develop healthier money management habits, and secure their financial future.",
    "longBio": "Tamoa Danielle leads Clarity Kollective LLC, specializing in transformative financial therapy. As CEO, she empowers clients to overcome financial challenges and achieve sustainable wellness. Tamoa’s journey includes personal recoveries from two bankruptcies and overcoming significant financial trauma, which fuels her passion for helping others transform their financial lives. As a licensed clinical mental health therapist and financial therapist, Tamoa integrates the emotional and psychological aspects into money management. Her holistic approach addresses the root causes of financial trauma, fostering a healthier relationship with money and combining practical advice with emotional support at the critical intersection of finances and mental well-being. Additionally, Tamoa serves as a personal to business development coach on the LUHV Plus platform, assisting entrepreneurs in clearing mental clutter and transforming into effective leaders with renewed mindsets for achieving their personal and business goals. Tamoa also heads Renew You Consulting LLC as a Credit Restoration Specialist. In this role, she expertly guides clients through the complexities of credit restoration, helping them rebuild their credit profiles to regain financial stability. A dedicated speaker, consultant, and advocate for financial empowerment, Tamoa is committed to renewing financial outlooks and transforming lives. Catch Tamoa Danielle on her YouTube channel, Financial Therapy to Prosperity, where she explores the intricate relationship between emotions and finances, delving into financial therapy, trauma, and the journey towards financial prosperity.",
    "previewBlurb": "Transforming financial trauma into empowerment through holistic healing and hope!",
    "profileUrl": "/experts/TamoaDanielleSmith.jpeg"
  },
  {
    "id": "20",
    "name": "Jennifer Calder",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/jennifer-a6qh/30minute",
    "expertise": "Individual and couples Financial Psychology Coaching, Inheritance Dynamics",
    "certifications": "Certified in Financial Psychology and Behavioral Finance, Masters in Social Work, Masters in Anthropology and Sociology",
    "song": "N/A",
    "yoe": "10",
    "clientele": "New couples, early career professionals, individuals receiving inheritance, and couples from diverse financial backgrounds seeking to navigate complex family wealth dynamics and parenting challenges.",
    "longBio": "I have been highlighted, featured, and interviewed in several news outlets: the Boston Globe, Women's World Daily, Seven Days, Fatherly, Vermont Edition, Healthy Love and Money. Jennifer holds a Masters degree in Sociology and Anthropology and a Masters degree in Social Work from the University of Vermont. In order to help people overcome and work through chronic financial stressors, Jennifer decided to extend her training with a graduate certificate program in Financial Psychology and Behavioral Finance from the Heider School of Business at Creighton University. From 2016-2018, as a student in the program, Jennifer was “the client” going through the process of addressing her own unconscious beliefs about money and connecting them to some of her unhelpful financial behaviors. She knows first-hand how addressing the psychology of money can improve wellbeing, relationships and financial security.",
    "previewBlurb": "Transforming financial struggles into empowerment through personal healing and insight!\n",
    "profileUrl": "/experts/JenniferCalder.jpeg"
  },
  {
    "id": "21",
    "name": "Nathan Astle",
    "title": "Financial Therapist",
    "bookingURL": "https://calendly.com/admin-yvmw/initial-consultation",
    "expertise": "Psychological aspects of financial life, Emotional relationship with money, Couples, Parents, Children, Family financial discussions, Mental health condition support, Trauma-informed financial healing, Communication barriers, Skill-based intervention\n",
    "certifications": "M.S. in Couples and Family Therapy, Certified Financial Therapist",
    "song": "\"Sweet Emotion\" by Aerosmith",
    "yoe": "8",
    "clientele": "I work with all ages, income levels, and am LGBTQ+ affirming. My specialty is with couples, but work with individuals and families often. I believe in making services as affordable as possible which is why I offer a sliding fee option.",
    "longBio": "Nate Astle is the CEO and Founder of the Financial Therapy Clinical Institute. He is a Marriage and Family Therapist and Certified Financial Therapist. He specializes in couples, emotions and money, and financial trauma. He has served as a past board member of the Financial Therapy Association, and has been featured in numerous outlets like the New York Times, Wall Street Journal, CNBC, USA Today, and TD Ameritrade.",
    "previewBlurb": "Transforming financial struggles into healing through compassionate, expert relationship guidance!",
    "profileUrl": ""
  }
]

export default TherapistList;