const TherapistsList = [
    {
      id: 1,
      name: "Paige Williams",
      title: "Financial Therapist",
      clients: ["Early to mid-career professional women in their mid 20's and 30's who are looking to build long-term wealth. ncome Level: Annual incomes ranging from $40,000 to $100,000. Occupation: A mix of salaried professionals, entrepreneurs, and freelancers.  Challenges: Struggle with balancing short-term wants and long-term goals, navigating credit, and establishing clear financial systems. "],
      certifications: "Bachelor's Degree in Biopsychology, Master's Degree in Medical Sciences – Liberty University (2022), Founder of the Millennium Money Master Program, Helped over 100 clients",
      yoe: "8",
      song:  "Upgrade U by Beyonce",
      profileUrl: "https://bersoriano.github.io/renavest-mobile/pwilliams.jpeg",
      introduction: "Money is more than numbers—it's a reflection of your journey, values, and dreams. Together, we'll turn financial stress into strength and build a future that honors where you come from and where you're going.",
      expertise: ["Debt management", "Saving", "Investing"],
      bookingURL: "https://millenniummoney.myclickfunnels.com/bookacall1",
      longBio: "I'm a passionate Money Coach and Online Content Creator dedicated to empowering women to take full control of their finances and build long-term wealth. In just 5 months, I paid off $3,000 in credit card debt, saved $5,000 in an emergency fund, and invested $10,000—all while juggling grad school and part-time jobs. This transformation inspired me to create the Millennium Money Master Program, a high-impact coaching program that has helped over 100 clients achieve financial confidence through crushing debt, investing, and strategic money management. My mission is to make personal finance fun, attainable, and attractive while inspiring others to take action, no matter where they’re starting",
      previewBlurb: "Empowering women to crush debt, invest smartly, and build lasting financial confidence."
    },
    {
      id: 2,
      name: "Dr. Shay Harris-Pierre",
      title: "Financial Therapist",
      clients: ["couples", "healthcare workers", "executives"],
      certifications: "CFT-I, Ph.D. Psychology",
      yoe: "12",
      song: "Independent Women by Destiny's Child",
      profileUrl: "https://i.pravatar.cc/300?img=25",
      introduction: "Your financial story is unique and deserves to be heard. Through our work together, we'll explore the emotional aspects of money while building practical skills for lasting financial wellness.",
      expertise: ["Investing", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 3,
      name: "Sarah Carr",
      title: "Financial Therapist",
      clients: ["retirees", "divorcees", "small business owners"],
      certifications: "CFT-I, LMFT",
      yoe: "15",
      song: "Take it Easy by Eagles",
      profileUrl: "https://i.pravatar.cc/300?img=26",
      introduction: "Life transitions bring both challenges and opportunities. I help you navigate financial changes with confidence, creating a roadmap that aligns with your values and supports your emotional wellbeing.",
      expertise: ["Retirement planning", "Divorce finances"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 4,
      name: "Nathan Astle",
      title: "Financial Therapist",
      clients: ["young professionals", "startup founders", "tech workers"],
      certifications: "CFT-I, CFA",
      yoe: "6",
      song: "Can't Hold Us by Macklemore",
      profileUrl: "https://i.pravatar.cc/300?img=33",
      introduction: "Financial success isn't just about spreadsheets—it's about understanding your relationship with money. Let's work together to create strategies that empower both your wallet and your mindset.",
      expertise: ["Investing", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 5,
      name: "Natasha Knox",
      title: "Financial Therapist",
      clients: ["women in tech", "immigrants", "career changers"],
      certifications: "CFT-I, CFP",
      yoe: "10",
      song: "Girl on Fire by Alicia Keys",
      profileUrl: "https://i.pravatar.cc/300?img=5",
      introduction: "Your financial journey is shaped by your experiences and cultural background. Together, we'll build a framework that embraces your identity while fostering financial growth and confidence.",
      expertise: ["Credit repair"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 6,
      name: "LaQueshia Clemons",
      title: "Financial Therapist",
      clients: ["first-generation professionals", "educators", "nonprofit workers"],
      certifications: "CFT-I, AFC",
      yoe: "7",
      song: "Started From The Bottom by Drake",
      profileUrl: "https://i.pravatar.cc/300?img=6",
      introduction: "Breaking generational patterns requires both courage and strategy. I'm here to help you write a new financial chapter while honoring your past and building a legacy for the future.",
      expertise: ["Student loans", "Budgeting and saving"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 7,
      name: "Mariah Hudler",
      title: "Financial Therapist",
      clients: ["creatives", "freelancers", "artists"],
      certifications: "CFT-I, LCSW",
      yoe: "9",
      song: "Freedom by Pharrell Williams",
      profileUrl: "https://i.pravatar.cc/300?img=7",
      introduction: "Creative spirits need unique financial solutions. Together, we'll craft a money approach that supports your artistic journey while building sustainable financial practices.",
      expertise: ["Debt management"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 8,
      name: "Emily Shull",
      title: "Financial Therapist",
      clients: ["parents", "families", "business owners"],
      certifications: "CFT-I, MBA",
      yoe: "11",
      song: "Beautiful Day by U2",
      profileUrl: "https://i.pravatar.cc/300?img=8",
      introduction: "Family dynamics and finances are deeply intertwined. I help you create harmony between your money goals and family values, building a legacy of financial wellness.",
      expertise: ["Family planning", "Estate planning"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 9,
      name: "Jasmine Ramirez",
      title: "Financial Therapist",
      clients: ["gen z", "students", "young entrepreneurs"],
      certifications: "CFT-I, AFC",
      yoe: "5",
      song: "Rich Girl by Gwen Stefani",
      profileUrl: "https://i.pravatar.cc/300?img=9",
      introduction: "Your generation faces unique financial challenges and opportunities. Let's harness your digital savvy and entrepreneurial spirit to create a money strategy that works for you.",
      expertise: ["Student loans", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 10,
      name: "Aitza",
      title: "Money Coach",
      clients: ["remote workers", "digital nomads", "freelancers"],
      certifications: "AFC, FFC",
      yoe: "4",
      song: "Location by Khalid",
      profileUrl: "https://i.pravatar.cc/300?img=10",
      introduction: "Location-independent living requires smart money management. I'll help you build financial systems that support your freedom while securing your future.",
      expertise: ["Small business finances", "Investing"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 11,
      name: "Freeman Lopez",
      title: "Money Coach",
      clients: ["immigrants", "international students", "expats"],
      certifications: "FFC, MBA",
      yoe: "6",
      song: "International Love by Pitbull",
      profileUrl: "https://i.pravatar.cc/300?img=11",
      introduction: "Navigating finances across borders comes with unique challenges. Together, we'll create a financial strategy that works globally while building wealth locally.",
      expertise: ["Credit repair", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 12,
      name: "Tiffany Grant",
      title: "Money Coach",
      clients: ["millennials", "side hustlers", "debt payoff"],
      certifications: "AFC, CFEI",
      yoe: "8",
      song: "Bills, Bills, Bills by Destiny's Child",
      profileUrl: "https://i.pravatar.cc/300?img=27",
      introduction: "Debt doesn't define you—it's just a chapter in your story. Let's create a plan to achieve financial freedom while building multiple income streams.",
      expertise: ["Debt management", "Credit repair"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 13,
      name: "Andrea Sampson",
      title: "Money Coach",
      clients: ["working moms", "career transitioners", "entrepreneurs"],
      certifications: "FFC, CMP",
      yoe: "5",
      song: "Run the World by Beyoncé",
      profileUrl: "https://i.pravatar.cc/300?img=28",
      introduction: "Balancing career, family, and finances takes strategy. I'll help you create systems that maximize your time and money while pursuing your dreams.",
      expertise: ["Family planning", "Small business finances"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 14,
      name: "Porscha Johnson",
      title: "Money Coach",
      clients: ["real estate investors", "business owners", "wealth builders"],
      certifications: "AFC, CRPC",
      yoe: "7",
      song: "All About the Benjamins by Puff Daddy",
      profileUrl: "https://i.pravatar.cc/300?img=29",
      introduction: "Building wealth is about making informed decisions today that compound tomorrow. Let's create a strategy that turns your financial goals into lasting legacy.",
      expertise: ["Investing", "Estate planning"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 15,
      name: "Shani Tene",
      title: "Money Coach",
      clients: ["creators", "influencers", "online entrepreneurs"],
      certifications: "FFC, CDFA",
      yoe: "4",
      song: "Boss Lady by Queen Naija",
      profileUrl: "https://i.pravatar.cc/300?img=15",
      introduction: "Digital success requires savvy money management. I'll help you turn your online influence into sustainable wealth while protecting your financial future.",
      expertise: ["Small business finances"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 16,
      name: "Jacqueline Schadeck",
      title: "Money Coach",
      clients: ["young professionals", "first-time investors", "career climbers"],
      certifications: "AFC, CPWA",
      yoe: "6",
      song: "Dreams and Nightmares by Meek Mill",
      profileUrl: "https://i.pravatar.cc/300?img=16",
      introduction: "Early career decisions shape your financial future. Together, we'll create a roadmap that maximizes your earning potential and builds lasting wealth.",
      expertise: ["Investing", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 17,
      name: "Paige Victoria Williams",
      title: "Money Coach",
      clients: ["women entrepreneurs", "startup founders", "small business owners"],
      certifications: "FFC, CBF",
      yoe: "5",
      song: "Work by Rihanna",
      profileUrl: "https://i.pravatar.cc/300?img=30",
      introduction: "Female founders need tailored financial strategies. I'll help you scale your business while building personal wealth and financial independence.",
      expertise: ["Small business finances", "Insurance"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 18,
      name: "Vince Hollerman",
      title: "Money Coach",
      clients: ["corporate executives", "managers", "high earners"],
      certifications: "AFC, CIMA",
      yoe: "9",
      song: "Power by Kanye West",
      profileUrl: "https://i.pravatar.cc/300?img=18",
      introduction: "High income should translate to high net worth. Let's optimize your finances to ensure your hard work creates lasting prosperity.",
      expertise: ["Estate planning", "Insurance"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 19,
      name: "Michael Rodriguez",
      title: "Money Coach",
      clients: ["latinos", "first-gen professionals", "immigrant families"],
      certifications: "FFC, CEPA",
      yoe: "7",
      song: "Mi Gente by J Balvin",
      profileUrl: "https://i.pravatar.cc/300?img=51",
      introduction: "Tu historia financiera es única. Juntos, crearemos un plan que honre tus raíces mientras construimos un futuro próspero para ti y tu familia.",
      expertise: ["Home buying", "Family planning"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 20,
      name: "Victoria Dambrozio",
      title: "Money Coach",
      clients: ["women in finance", "career changers", "professionals"],
      certifications: "AFC, FPQP",
      yoe: "6",
      song: "Woman by Doja Cat",
      profileUrl: "https://i.pravatar.cc/300?img=20",
      introduction: "Financial empowerment starts with understanding your worth. Let's create strategies that align with your ambitions and secure your financial independence.",
      expertise: ["Investing"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 21,
      name: "Jessenia",
      title: "Financial Therapist",
      clients: ["hispanic families", "business owners", "first-time investors"],
      certifications: "CFT-I, AFC",
      yoe: "8",
      song: "Vivir Mi Vida by Marc Anthony",
      profileUrl: "https://i.pravatar.cc/300?img=21",
      introduction: "El dinero es más que números—es el reflejo de tus valores y sueños. Juntos, transformaremos el estrés financiero en fortaleza para construir un futuro próspero.",
      expertise: ["Home buying", "Personal finance for beginners"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    },
    {
      id: 22,
      name: "Justin DeFoor",
      title: "Money Coach",
      clients: ["athletes", "entertainers", "high-net-worth individuals"],
      certifications: "FFC, CPWA",
      yoe: "10",
      song: "All I Do Is Win by DJ Khaled",
      profileUrl: "https://i.pravatar.cc/300?img33",
      introduction: "Peak performance in finance requires the same discipline as in your craft. Let's build a strategy that protects and grows your wealth for the long game.",
      expertise: ["Estate planning", "Insurance"],
      bookingURL: "",
      longBio: "",
      previewBlurb: ""
    }
];
const TherapistsListOld = [
  {
    id: 1,
    name: "Paige Williams",
    title: "Financial Therapist",
    clients: ["Early to mid-career professional women in their mid 20's and 30's who are looking to build long-term wealth. ncome Level: Annual incomes ranging from $40,000 to $100,000. Occupation: A mix of salaried professionals, entrepreneurs, and freelancers.  Challenges: Struggle with balancing short-term wants and long-term goals, navigating credit, and establishing clear financial systems. "],
    certifications: "Bachelor's Degree in Biopsychology, Master's Degree in Medical Sciences – Liberty University (2022), Founder of the Millennium Money Master Program, Helped over 100 clients",
    yoe: "8",
    song:  "Upgrade U by Beyonce",
    profileUrl: "https://bersoriano.github.io/renavest-mobile/pwilliams.jpeg",
    introduction: "Money is more than numbers—it's a reflection of your journey, values, and dreams. Together, we'll turn financial stress into strength and build a future that honors where you come from and where you're going.",
    expertise: ["Debt management", "Saving", "Investing"],
    bookingURL: "https://millenniummoney.myclickfunnels.com/bookacall1",
    longBio: "I'm a passionate Money Coach and Online Content Creator dedicated to empowering women to take full control of their finances and build long-term wealth. In just 5 months, I paid off $3,000 in credit card debt, saved $5,000 in an emergency fund, and invested $10,000—all while juggling grad school and part-time jobs. This transformation inspired me to create the Millennium Money Master Program, a high-impact coaching program that has helped over 100 clients achieve financial confidence through crushing debt, investing, and strategic money management. My mission is to make personal finance fun, attainable, and attractive while inspiring others to take action, no matter where they’re starting",
    previewBlurb: "Empowering women to crush debt, invest smartly, and build lasting financial confidence."
  },
  {
    id: 2,
    name: "Dr. Shay Harris-Pierre",
    title: "Financial Therapist",
    clients: ["couples", "healthcare workers", "executives"],
    certifications: "CFT-I, Ph.D. Psychology",
    yoe: "12",
    song: "Independent Women by Destiny's Child",
    profileUrl: "https://i.pravatar.cc/300?img=25",
    introduction: "Your financial story is unique and deserves to be heard. Through our work together, we'll explore the emotional aspects of money while building practical skills for lasting financial wellness.",
    expertise: ["Investing", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 3,
    name: "Sarah Carr",
    title: "Financial Therapist",
    clients: ["retirees", "divorcees", "small business owners"],
    certifications: "CFT-I, LMFT",
    yoe: "15",
    song: "Take it Easy by Eagles",
    profileUrl: "https://i.pravatar.cc/300?img=26",
    introduction: "Life transitions bring both challenges and opportunities. I help you navigate financial changes with confidence, creating a roadmap that aligns with your values and supports your emotional wellbeing.",
    expertise: ["Retirement planning", "Divorce finances"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 4,
    name: "Nathan Astle",
    title: "Financial Therapist",
    clients: ["young professionals", "startup founders", "tech workers"],
    certifications: "CFT-I, CFA",
    yoe: "6",
    song: "Can't Hold Us by Macklemore",
    profileUrl: "https://i.pravatar.cc/300?img=33",
    introduction: "Financial success isn't just about spreadsheets—it's about understanding your relationship with money. Let's work together to create strategies that empower both your wallet and your mindset.",
    expertise: ["Investing", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 5,
    name: "Natasha Knox",
    title: "Financial Therapist",
    clients: ["women in tech", "immigrants", "career changers"],
    certifications: "CFT-I, CFP",
    yoe: "10",
    song: "Girl on Fire by Alicia Keys",
    profileUrl: "https://i.pravatar.cc/300?img=5",
    introduction: "Your financial journey is shaped by your experiences and cultural background. Together, we'll build a framework that embraces your identity while fostering financial growth and confidence.",
    expertise: ["Credit repair"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 6,
    name: "LaQueshia Clemons",
    title: "Financial Therapist",
    clients: ["first-generation professionals", "educators", "nonprofit workers"],
    certifications: "CFT-I, AFC",
    yoe: "7",
    song: "Started From The Bottom by Drake",
    profileUrl: "https://i.pravatar.cc/300?img=6",
    introduction: "Breaking generational patterns requires both courage and strategy. I'm here to help you write a new financial chapter while honoring your past and building a legacy for the future.",
    expertise: ["Student loans", "Budgeting and saving"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 7,
    name: "Mariah Hudler",
    title: "Financial Therapist",
    clients: ["creatives", "freelancers", "artists"],
    certifications: "CFT-I, LCSW",
    yoe: "9",
    song: "Freedom by Pharrell Williams",
    profileUrl: "https://i.pravatar.cc/300?img=7",
    introduction: "Creative spirits need unique financial solutions. Together, we'll craft a money approach that supports your artistic journey while building sustainable financial practices.",
    expertise: ["Debt management"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 8,
    name: "Emily Shull",
    title: "Financial Therapist",
    clients: ["parents", "families", "business owners"],
    certifications: "CFT-I, MBA",
    yoe: "11",
    song: "Beautiful Day by U2",
    profileUrl: "https://i.pravatar.cc/300?img=8",
    introduction: "Family dynamics and finances are deeply intertwined. I help you create harmony between your money goals and family values, building a legacy of financial wellness.",
    expertise: ["Family planning", "Estate planning"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 9,
    name: "Jasmine Ramirez",
    title: "Financial Therapist",
    clients: ["gen z", "students", "young entrepreneurs"],
    certifications: "CFT-I, AFC",
    yoe: "5",
    song: "Rich Girl by Gwen Stefani",
    profileUrl: "https://i.pravatar.cc/300?img=9",
    introduction: "Your generation faces unique financial challenges and opportunities. Let's harness your digital savvy and entrepreneurial spirit to create a money strategy that works for you.",
    expertise: ["Student loans", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 10,
    name: "Aitza",
    title: "Money Coach",
    clients: ["remote workers", "digital nomads", "freelancers"],
    certifications: "AFC, FFC",
    yoe: "4",
    song: "Location by Khalid",
    profileUrl: "https://i.pravatar.cc/300?img=10",
    introduction: "Location-independent living requires smart money management. I'll help you build financial systems that support your freedom while securing your future.",
    expertise: ["Small business finances", "Investing"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 11,
    name: "Freeman Lopez",
    title: "Money Coach",
    clients: ["immigrants", "international students", "expats"],
    certifications: "FFC, MBA",
    yoe: "6",
    song: "International Love by Pitbull",
    profileUrl: "https://i.pravatar.cc/300?img=11",
    introduction: "Navigating finances across borders comes with unique challenges. Together, we'll create a financial strategy that works globally while building wealth locally.",
    expertise: ["Credit repair", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 12,
    name: "Tiffany Grant",
    title: "Money Coach",
    clients: ["millennials", "side hustlers", "debt payoff"],
    certifications: "AFC, CFEI",
    yoe: "8",
    song: "Bills, Bills, Bills by Destiny's Child",
    profileUrl: "https://i.pravatar.cc/300?img=27",
    introduction: "Debt doesn't define you—it's just a chapter in your story. Let's create a plan to achieve financial freedom while building multiple income streams.",
    expertise: ["Debt management", "Credit repair"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 13,
    name: "Andrea Sampson",
    title: "Money Coach",
    clients: ["working moms", "career transitioners", "entrepreneurs"],
    certifications: "FFC, CMP",
    yoe: "5",
    song: "Run the World by Beyoncé",
    profileUrl: "https://i.pravatar.cc/300?img=28",
    introduction: "Balancing career, family, and finances takes strategy. I'll help you create systems that maximize your time and money while pursuing your dreams.",
    expertise: ["Family planning", "Small business finances"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 14,
    name: "Porscha Johnson",
    title: "Money Coach",
    clients: ["real estate investors", "business owners", "wealth builders"],
    certifications: "AFC, CRPC",
    yoe: "7",
    song: "All About the Benjamins by Puff Daddy",
    profileUrl: "https://i.pravatar.cc/300?img=29",
    introduction: "Building wealth is about making informed decisions today that compound tomorrow. Let's create a strategy that turns your financial goals into lasting legacy.",
    expertise: ["Investing", "Estate planning"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 15,
    name: "Shani Tene",
    title: "Money Coach",
    clients: ["creators", "influencers", "online entrepreneurs"],
    certifications: "FFC, CDFA",
    yoe: "4",
    song: "Boss Lady by Queen Naija",
    profileUrl: "https://i.pravatar.cc/300?img=15",
    introduction: "Digital success requires savvy money management. I'll help you turn your online influence into sustainable wealth while protecting your financial future.",
    expertise: ["Small business finances"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 16,
    name: "Jacqueline Schadeck",
    title: "Money Coach",
    clients: ["young professionals", "first-time investors", "career climbers"],
    certifications: "AFC, CPWA",
    yoe: "6",
    song: "Dreams and Nightmares by Meek Mill",
    profileUrl: "https://i.pravatar.cc/300?img=16",
    introduction: "Early career decisions shape your financial future. Together, we'll create a roadmap that maximizes your earning potential and builds lasting wealth.",
    expertise: ["Investing", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 17,
    name: "Paige Victoria Williams",
    title: "Money Coach",
    clients: ["women entrepreneurs", "startup founders", "small business owners"],
    certifications: "FFC, CBF",
    yoe: "5",
    song: "Work by Rihanna",
    profileUrl: "https://i.pravatar.cc/300?img=30",
    introduction: "Female founders need tailored financial strategies. I'll help you scale your business while building personal wealth and financial independence.",
    expertise: ["Small business finances", "Insurance"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 18,
    name: "Vince Hollerman",
    title: "Money Coach",
    clients: ["corporate executives", "managers", "high earners"],
    certifications: "AFC, CIMA",
    yoe: "9",
    song: "Power by Kanye West",
    profileUrl: "https://i.pravatar.cc/300?img=18",
    introduction: "High income should translate to high net worth. Let's optimize your finances to ensure your hard work creates lasting prosperity.",
    expertise: ["Estate planning", "Insurance"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 19,
    name: "Michael Rodriguez",
    title: "Money Coach",
    clients: ["latinos", "first-gen professionals", "immigrant families"],
    certifications: "FFC, CEPA",
    yoe: "7",
    song: "Mi Gente by J Balvin",
    profileUrl: "https://i.pravatar.cc/300?img=51",
    introduction: "Tu historia financiera es única. Juntos, crearemos un plan que honre tus raíces mientras construimos un futuro próspero para ti y tu familia.",
    expertise: ["Home buying", "Family planning"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 20,
    name: "Victoria Dambrozio",
    title: "Money Coach",
    clients: ["women in finance", "career changers", "professionals"],
    certifications: "AFC, FPQP",
    yoe: "6",
    song: "Woman by Doja Cat",
    profileUrl: "https://i.pravatar.cc/300?img=20",
    introduction: "Financial empowerment starts with understanding your worth. Let's create strategies that align with your ambitions and secure your financial independence.",
    expertise: ["Investing"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 21,
    name: "Jessenia",
    title: "Financial Therapist",
    clients: ["hispanic families", "business owners", "first-time investors"],
    certifications: "CFT-I, AFC",
    yoe: "8",
    song: "Vivir Mi Vida by Marc Anthony",
    profileUrl: "https://i.pravatar.cc/300?img=21",
    introduction: "El dinero es más que números—es el reflejo de tus valores y sueños. Juntos, transformaremos el estrés financiero en fortaleza para construir un futuro próspero.",
    expertise: ["Home buying", "Personal finance for beginners"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  },
  {
    id: 22,
    name: "Justin DeFoor",
    title: "Money Coach",
    clients: ["athletes", "entertainers", "high-net-worth individuals"],
    certifications: "FFC, CPWA",
    yoe: "10",
    song: "All I Do Is Win by DJ Khaled",
    profileUrl: "https://i.pravatar.cc/300?img33",
    introduction: "Peak performance in finance requires the same discipline as in your craft. Let's build a strategy that protects and grows your wealth for the long game.",
    expertise: ["Estate planning", "Insurance"],
    bookingURL: "",
    longBio: "",
    previewBlurb: ""
  }
];

const TherapistListFinal = [
{
  id: 1,
  name: "Paige Williams",
  title: "Fin Coach",
  bookingURL: "https://millenniummoney.myclickfunnels.com/bookacall1",
  expertise: "Debt management, Saving, Investing",
  certifications: "Bachelor's Degree in Biopsychology, Master's Degree in Medical Sciences – Liberty University (2022), Founder of the Millennium Money Master Program, Helped over 100 clients",
  song: "Upgrade U by Beyonce",
  yoe: "8",
  clientele: "Early to mid-career professional women in their mid 20's and 30's who are looking to build long-term wealth - Income Level: Annual incomes ranging from $40,000 to $100,000. - Occupation: A mix of salaried professionals, entrepreneurs, and freelancers - Challenges: Struggle with balancing short-term wants and long-term goals, navigating credit, and establishing clear financial systems.",
  longBio: "I'm a passionate Money Coach and Online Content Creator dedicated to empowering women to take full control of their finances and build long-term wealth. In just 5 months, I paid off $3,000 in credit card debt, saved $5,000 in an emergency fund, and invested $10,000—all while juggling grad school and part-time jobs. This transformation inspired me to create the Millennium Money Master Program, a high-impact coaching program that has helped over 100 clients achieve financial confidence through crushing debt, investing, and strategic money management. My mission is to make personal finance fun, attainable, and attractive while inspiring others to take action, no matter where they're starting",
  previewBlurb: "Empowering women to crush debt, invest smartly, and build lasting financial confidence."
},
{
  id: 2,
  name: "Constance McConnell",
  title: "Fin Therapist",
  bookingURL: "https://calendly.com/constance-courage2heal/30min",
  expertise: "Major life and Financial Changes, Budgeting",
  certifications: "Licensed Clinical Social Worker, Certified Financial Social Worker, Therapist",
  song: "Golden by Jill Scott",
  yoe: "10+",
  clientele: "20-65 years old, Historically marginalized populations (Black, Latinx, Native American, Women, LGBTQ communities), Identify with the upper middle socioeconomic class, Doesn't mind telling their story via mindful journaling.",
  longBio: "Constance is a LCSW, author, business owner, financial therapist and creative who specializes in working with individuals who are experiencing major life and financial changes. She is also a certified financial social worker and helps clients who want to improve their relationship with money. Constance is the author of a guided journal called, \"My Very Own Affirming Guided Journal A-Z\" and launched a t-shirt line with designs that feature positive affirmations. She has practiced for 12 years and most of her clients are a part of the BIPOC and LGBTQ+ communities. Constance has been a featured professional guest on the following podcasts and media platforms: \"Personal Finance with Leila\", \"Budget Simple\" \"SocialWorkerRants\" \"AboutthatWallet\"and \"FIRE Social Worker.\"",
  previewBlurb: "A financial therapist and author, enhancing relationships with money through empowerment!"
},
{
  id: 3,
  name: "Michele Paiva",
  title: "Fin Therapist",
  bookingURL: "https://calendly.com/paiva/corporate-client",
  expertise: "Business Management, Family Planning, Couples, Clinical autism specialist",
  certifications: "Licensed Psychotherapist specializing in Trauma and Financial Therapy, Certified Clinical Autism Specialist, Certified Financial Educator, Certified Financial Social Worker, Lifestyle Science Certified, Certified Clinical Meditation (Through University of Mass)",
  song: "Ain't Misbehavin by Fats Waller",
  yoe: "10+",
  clientele: "21 - 55, Mid Income, Millennials enjoy that I've been there, done-that, and lived to tell; older clients appreciate that I've already put children through college, invested in property, etc., beyond \"just getting out of debt\" etc.",
  longBio: "Michele Paiva is a financial therapist, trauma therapist, fractional CMO, and publicist with over 30 years of experience helping individuals and businesses thrive. Millennials value her relatable, \"I've been there\" approach, while Boomers appreciate her wisdom from successfully living through life's financial challenges. Michele's work focuses on uncovering the emotions beneath financial struggles, resolving couples' money conflicts, and empowering clients to showcase their value, build abundance, and create lasting change. Michele has autism and is also a certified clinical autism specialist who enjoys helping neurodivergent employees regain their feelings and finances. In 2023, she was voted top 100 publicists out of 14,000. She likes Tofu.",
  previewBlurb: "A casual approach to emotional depth and elegant living."
},
{
  id: 4,
  name: "Justin DeFoor",
  title: "Fin Coach",
  bookingURL: "https://calendly.com/tgcfinancialgroup",
  expertise: "Budgeting, Savings, Growth, Credit, Tax Planning",
  certifications: "MBA, Certificate in Life Coaching, Life Insurance License",
  song: "You Will Win by Jekalyn Carr",
  yoe: "5",
  clientele: "18- 50, Income from $18,000 to $100,000, Any ethnicity and background",
  longBio: "I started my entrepreneur lifestyle as a business consultant. After about a year I entered into the financial services industry to help more people. I believe my purpose is to help people become financially free and create generational wealth. Through this I have helped a lot of individuals and families build the lifestyle that they want by understanding the fundamentals of finance and creating good financial habits that will benefit them and their children. I've been in this industry for 5 years and now look to build people mentally, emotionally, physically, spiritually, and financially to walk in balance while living in purpose in every area of their lives.",
  previewBlurb: "Empowering financial freedom and generational wealth for all!"
},
{
  id: 5,
  name: "Aitzarelys Negrón",
  title: "Fin Coach",
  bookingURL: "https://StrategiesandTEA.as.me/?appointmentType=72189521",
  expertise: "Entrepreneurship, Paycheck to Purpose, mindset shifts, money audits, customized budgeting strategies, business bookkeeping, time tracking, business essentials, and profit management, debt management, burnout, cash flow",
  certifications: "Certified Public Accountant (CPA), QuickBooks Online Certified, ProAdvisor, Accredited Financial Counselor (Studying/In Process)",
  song: "Level Up by Ciara",
  yoe: "10+",
  clientele: "Professionals, Aspiring entrepreneurs, 25–45 years old, Income: $70,000–$150,000+",
  longBio: "Aitza is a passionate financial coach, accountant, and entrepreneur dedicated to helping professionals and aspiring business owners achieve financial clarity and time freedom. With a background as a CPA and years of experience in personal finance and business management, she empowers her clients to bridge the gap between their current reality and their ideal lifestyle. Aitza's journey into financial coaching was inspired by her own transformational story—turning her life around in high school with the support of a mentor, she now dedicates her career to helping others see possibilities and take control of their futures. Her coaching program, moneyFLOW$™ Academy, guides high-earning professionals through mastering personal finances, reducing debt, and building sustainable businesses. In addition to coaching, Aitza specializes in bookkeeping, bookkeeping diagnostics, Profit First implementation, and financial clean-ups, ensuring business owners have the tools they need for long-term profitability. Her clients have achieved remarkable results, from saving thousands of dollars to confidently launching businesses that align with their goals and values. Aitza's mission is to create financial confidence and economic resilience for her clients, equipping them to build wealth and lead change for themselves, their families, and their communities.",
  previewBlurb: "Transforming finances, empowering dreams, and creating lasting wealth!"
},
{
  id: 6,
  name: "Maureen Kelley",
  title: "Fin Therapist",
  bookingURL: "https://calendly.com/mk-maureenkelley",
  expertise: "Family, wealth management, positive psychology",
  certifications: "BS, University of Rhode Island Graduate Cert Financial Therapy, Kansas State Univ Executive Women's Leadership, The Wharton School - Certification Applied Positive Psychology, Univ of Penn Certified Financial Therapist (CFT), Certified Financial Behavior Specialist (FBS), Accredited Wealth Management Advisor (AWMA), Certified Family Wealth Advisor (CFWA), Certified Family Coach(CFC), Certified Co-Parenting Specialist",
  song: "You've Got a Friend In Me by Randy Newman",
  yoe: "10+",
  clientele: "People from all walks of life. Young adults, individuals, co-parents, couples and families, She has helped those who struggle with making ends meet, people navigating divorce issues, to multi generational complex families of wealth.",
  longBio: "Maureen Kelley has more than 30 years' experience helping families navigate the complex intersection of economics and emotions. As a seasoned family dynamics coach and family wealth consultant, she's dedicated to creating a safe space for you to share the ups and downs of your financial journey. Maureen works to dismantle the stigma surrounding these conversations, making hard-to-talk-about topics a lot easier. Having held senior positions at financial institutions like BOK Financial Private Wealth and Wells Fargo Private Bank, Maureen offers years of expertise in wealth management and positive psychology, helping you improve your financial life by improving your relationship with yourself and your loved ones. Working with Maureen, you'll rewrite your \"money scripts\"—the narratives we develop around wealth in childhood—and better understand how your past shapes your present views on money. As the founder of a family dynamics and financial coaching practice, Maureen's dedication to family is evident. Her services have been utilized by people of all walks of life, including young adults, co-parents, couples, and multi-generational families. Through financial therapy and coaching, you can overcome anxiety, guilt or shame surrounding money, and develop financial literacy to achieve holistic success. With less stress around money management, you can spend more time focusing on the things that really matter, like spending time with the ones you love.",
  previewBlurb: "Transform your relationship with money to enhance life and strengthen family connections."
},
{
  id: 7,
  name: "Tiffany Grant",
  title: "Fin Coach",
  bookingURL: "https://calendly.com/moneytalkwitht/coaching",
  expertise: "Personal finance, side hustles, business growth, money management",
  certifications: "MBA, AFC, SHRM-CP",
  song: "Lean on Me by Bill Withers",
  yoe: "8",
  clientele: "25-45, any gender, income up to $150,000, looking for help with budgeting and goal setting",
  longBio: "Tiffany Grant, AFC®, is a dedicated Accredited Financial Counselor, sought-after speaker, and founder of Money Talk With Tiff. Renowned for her ability to make personal finance approachable and relatable, Tiffany has made significant contributions as a financial educator, coach, blogger, and podcaster. Her expert advice on side hustles, business growth, and money management has been featured on platforms like Forbes, CNBC, Yahoo Finance, Business Insider, MSN, and ESSENCE. Tiffany's passion lies in empowering others to gain control over their finances through practical education and down-to-earth insights. Her engaging style and actionable guidance have helped countless individuals build financial confidence and clarity. Beyond her professional accolades, Tiffany's academic background includes a Bachelor of Business Administration and Management from the University of North Carolina at Pembroke and a Master of Business Administration (MBA) from the University of North Carolina at Greensboro. She also holds the SHRM-CP credential and is a certified Lean Six Sigma Yellow Belt, reflecting her diverse expertise and dedication to continuous learning.",
  previewBlurb: "Empowering financial freedom through practical education and relatable money management insights."
},
{
  id: 8,
  name: "Tyana Ingram",
  title: "Fin Social Work",
  bookingURL: "https://calendly.com/tingram-xdc/financial-wellness-counsulting",
  Expertise: "Financial Healing, Mindset, financial wellness",
  Certifications: "ASW (Associate Clinical Social Worker), CFSW (Certified Financial Social Worker), CFEI (Certified Financial Educational Instructor)",
  song: "Optimistic by Sounds of Blackness",
  yoe: "10+",
  clientele: "Underserved communities, Professionals, low-middle income, women entrepreneurs, domestic violence survivors, Christian",
  longBio: "Tyana Ingram is the CPO and Co-Founder of the Financial Social Work Collaborative™ and is the Founder of Financial Healing Circles™, a financial wellness business that empowers underserved communities to heal their money wounds and achieve financial peace of mind. Her mission is to disrupt the cycle of money trauma utilizing the Financial Social Work framework combined with a mind-body-soul approach to deliver financial wellness services. She is an Associate Clinical Social Worker, Certified Financial Social Worker, and Financial Education Instructor based out of California and has dedicated her career to equipping people with the tools they need to live their best lives.",
  previewBlurb: "Empowering communities to heal money wounds and achieve financial peace through holistic wellness."
},
{
  id: 9,
  name: "Vince Hollerman",
  title: "Fin Coach",
  bookingURL: "https://app.acuityscheduling.com/schedule/8d3ad975",
  Expertise: "Previously investment and life insurance licensed. (No longer holds licenses)",
  Certifications: "Previously investment and life insurance licensed. (No longer holds licenses)",
  song: "N/A",
  yoe: "8",
  clientele: "25-45 year olds, 50/50 Male to Female, income level: $50,000+, 9-5 Professionals, Small Business Owners",
  longBio: "Vince Hollerman, Coach Vince, is a Money Coach & Digital Creator specializing in helping millennials sort or their finances and stream line their path to financial freedom. He focuses on instilling great money habits for saving, budgeting & investing by developing your money mindset and putting money systems into place to help you reach your financial goals. With over 600,000 followers and supporters across social media, Vince has built a successful online Financial Education & Coaching Platform called IAmYourMoneyCoach.com that impacts and transforms the finances of those looking to take back control of their money.",
  previewBlurb: "Empowering millennials to achieve financial freedom through mindset shifts and effective money systems"
},
{
  id: 10,
  name: "Jaelyn Vickery",
  title: "Fin Therapist",
  bookingURL: "https://outlook.office.com/bookwithme/user/dbdc3761a936461793e506df25358b91@illinois.edu/meetingtype/_T3Sy3d-XkuptOwOzGAk-A2?bookingcode=3c26242c-7647-4395-9aea-135ffebbf651&anonymous&ep=mLinkFromTile",
  Expertise: "Dimensional Wealth, holistic abundance, financial empowerment, financial therapy, mindset",
  Certifications: "B.A. Liberal Arts & Sciences, Psychology M.S. Social Work, Healthcare/Mental Health LSW, Licensed Social Worker, Certified Integrated Behavioral Health Technician, 8 Dimensions of Wellness Guidebook Author (UIUC), CFT-I - Certified Financial Therapist *In Process, AFC - Accredited Financial Counselor *In Process",
  song: "You Make My Dreams by Hall & Oates",
  yoe: "1",
  clientele: "Aged 18-45 who are navigating life transitions, Diverse genders, Diverse income levels and backgrounds",
  longBio: "Jaelyn (Jae) Vickery is a dynamic force in the world of holistic wellness and financial empowerment. As a financial therapist, entrepreneur, and creator of the acclaimed podcast Finance Fitness Finesse, Jae is dedicated to helping individuals build their wealth with wellness. Through her business, Dimensional Wealth LLC, she champions a momentum mindset—encouraging actionable steps toward abundance and longevity rather than waiting on fleeting motivation. With extensive experience researching and working in eating disorder therapy, Jae has explored the complex relationship between eating disorders and financial strain. She particularly enjoys working with individuals who seek a higher understanding of themselves and value the accountability to embrace the challenge of building and sustaining new habits. Jae is dedicated to helping individuals break free from the cycle of compulsion, consumption, and control. Jae's straightforward compassionate accountability approach brings purpose to every conversation to help her network diversify their knowledge portfolios. She's here to help you connect the dots between wealth and wellness and isn't afraid to tell you why \"you're not woke, you're broke.\" In her free time, Jae embraces free movement through exercise, explores nature with her dog Bibble, and indulges her love for art. A devoted plant mom and chess enthusiast, she brings creativity and strategy to everything she does.",
  previewBlurb: "Empowering holistic wealth and wellness through financial therapy and mindset transformation."
},
{
  id: 11,
  name: "Shani Tené",
  title: "Fin Coach",
  bookingURL: "https://shanitene.com/levelup",
  Expertise: "Budgeting and saving, Investing and debt reduction",
  Certifications: "N/A",
  song: "Stronger Together",
  yoe: "10+",
  clientele: "Millennials & Gen X, Middle Class Females",
  longBio: "Shani Tené is a passionate Money Coach, financial educator and speaker, dedicated to helping individuals achieve financial freedom through a faith-inspired approach. Merging extensive financial knowledge with spiritual principles, Shani empowers clients to enhance their income, manage debt, and invest wisely, ensuring their financial goals reflect their personal values. Her holistic strategy not only boosts financial health but also fosters spiritual richness, guiding clients towards sustainable wealth and true independence.",
  previewBlurb: "Empowering financial freedom through faith-based coaching and holistic money management."
},
{
  id: 12,
  name: "BreAnna Plummer",
  title: "Fin Social Work",
  bookingURL: "https://calendly.com/bplummerconsciouschoicestherapy/financialwellness",
  Expertise: "Money Mindset, Budgeting & saving, Debt",
  Certifications: "Licensed Master Social Worker (LMSW), Certified Financial Social Worker (CFSW), Certified Domestic Violence Specialist Level 1 (CDVSI)",
  song: "One Step At A Time by Jordan Sparks",
  yoe: "9",
  clientele: "Age 30-45 who identify as BIPOC, Income levels range from 100,000-300,000 annually, No guidance or support in improving financial stability and saving habits, Symptoms such as stress, depression, PTSD and anxiety = main money concern",
  longBio: "I have been a clinical social worker and advocate for wellness for 9 years. I earned my BSW (2015) and MSW (2017) from Wayne State University. Over my career I have worked with families of Head Start, survivors of crime, survivors of homelessness and financial trauma, planned community events for survivors and managed programs for suicide prevention. I became a certified financial social worker in August 2024. The highs and lows of my own financial journey led me to practice financial social work. I utilize my skills and professional expertise to help clients gain mental and financial stability through one-on-one support. Working to help individuals have less stress and anxiety about money while decreasing their debt and increasing their savings is my passion. In our 45-60 minute one on one sessions, clients will gain holistic and practical tools to transform into a mindful money manager!",
  previewBlurb: "Empowering mental and financial stability through holistic 1on1 support and practical tools."
},
{
  id: 13,
  name: "Monica Bradshaw",
  title: "Fin Coach",
  bookingURL: "https://calendly.com/mbradshaw-2/rpcoaching",
  Expertise: "Wealth building, retirement",
  Certifications: "Certified Financial Coach, Certified Trauma Coach",
  song: "Titanium by David Guetta",
  yoe: "3",
  clientele: "45 - 60 years old, Sandwich generation, Household income $120k.",
  longBio: "I began my career in 1994 at Paulson Investments and have since built a diverse background, including roles as a licensed stockbroker, real estate agent, trauma counselor, IT manager, certified Scrum Master, and bookkeeper. Despite high income and prestigious credentials, I found myself struggling financially, with no progress toward generational wealth and living paycheck to paycheck. After confronting my money trauma and mindset, I developed a transformational approach combining financial strategies with personal growth techniques. This led me to coach others, incorporating neuropsychology, manifestation, and assessments. I help people go beyond financial knowledge to achieve true transformation, enabling lasting success. My journey has been shaped by extensive study in areas like NLP, neuroscience, and wealth-building, and I now share my step-by-step method to help others achieve financial and personal bliss.",
  previewBlurb: "Transforming financial struggles into lasting success through holistic coaching and personal growth."
}  
]

export default TherapistListFinal;